CREATE TABLE IF NOT EXISTS turfs(
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    location VARCHAR(200) NOT NULL,
    price_per_hour INTEGER NOT NULL,
    descriptin TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);